# Generated by Django 2.0.1 on 2018-01-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20180122_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
